#!/usr/bin/env python3
"""
Compare harmonic calculation output vs maree.info reference data.
Reads:
  - harmonic_2026.csv  (generated by TideValidation sketch)
  - mareeinfo_le_palais_2026.csv  (scraped from maree.info)
"""

import csv
import datetime as dt
import re
import sys
from pathlib import Path
from collections import defaultdict

HARMONIC_FILE = 'harmonic_2026.csv'
REFERENCE_FILE = 'mareeinfo_le_palais_2026.csv'


# ── Load reference (maree.info) ────────────────────────────────────────────────
def load_reference(path):
    """Returns dict: date → list of (time, height, is_high, coeff)"""
    by_date = defaultdict(list)
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            d = dt.datetime.strptime(row['datetime'], '%Y-%m-%d %H:%M')
            coeff = int(row['coefficient']) if row['coefficient'] else None
            by_date[d.date()].append((d.time(), float(row['height_m']),
                                      row['is_high_tide'] == 'H', coeff))
    return by_date


# ── Load harmonic CSV ──────────────────────────────────────────────────────────
def load_harmonic(path):
    """Returns dict: date → list of (time, height, is_high, coeff)"""
    by_date = defaultdict(list)
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            date = dt.date.fromisoformat(row['date'])
            for i in range(1, 5):
                t_type = row.get(f'Event{i}_Type', '')
                t_time = row.get(f'Event{i}_Time', '')
                t_height = row.get(f'Event{i}_Height', '')
                if not t_type or not t_time:
                    continue
                try:
                    time_obj = dt.datetime.strptime(t_time, '%H:%M').time()
                    height = float(t_height)
                    coeff_str = row.get(f'Event{i}_Coeff', '')
                    coeff = int(coeff_str) if coeff_str else None
                    is_high = t_type == 'HT'
                    by_date[date].append((time_obj, height, is_high, coeff))
                except ValueError:
                    continue
    return by_date


# ── Match tides between two datasets ──────────────────────────────────────────
def time_diff_minutes(t1: dt.time, t2: dt.time) -> float:
    """Signed difference t1 - t2 in minutes."""
    d1 = dt.datetime.combine(dt.date.today(), t1)
    d2 = dt.datetime.combine(dt.date.today(), t2)
    return (d1 - d2).total_seconds() / 60


def compare_day(harm_tides, ref_tides):
    """
    Match tides by nearest time within the same type (H/L).
    Uses greedy nearest-neighbor to avoid order-mismatch on 3-tide days.
    """
    diffs = []
    harm_highs = [(t, h, c) for t, h, is_high, c in harm_tides if is_high]
    harm_lows  = [(t, h, c) for t, h, is_high, c in harm_tides if not is_high]
    ref_highs  = [(t, h, c) for t, h, is_high, c in ref_tides  if is_high]
    ref_lows   = [(t, h, c) for t, h, is_high, c in ref_tides  if not is_high]

    def nearest_match(harm_list, ref_list, tide_type):
        used = set()
        for ht, hh, hc in harm_list:
            best_idx, best_diff = None, float('inf')
            for i, (rt, rh, rc) in enumerate(ref_list):
                if i in used:
                    continue
                diff = abs(time_diff_minutes(ht, rt))
                if diff < best_diff:
                    best_diff, best_idx = diff, i
            if best_idx is not None and best_diff < 120:  # sanity: within 2h
                rt, rh, rc = ref_list[best_idx]
                used.add(best_idx)
                diffs.append((tide_type, time_diff_minutes(ht, rt), hh - rh, hc, rc))

    nearest_match(harm_highs, ref_highs, 'HT')
    nearest_match(harm_lows,  ref_lows,  'LT')
    return diffs


def fmt_time(t: dt.time) -> str:
    return t.strftime('%H:%M')


def main():
    ref = load_reference(REFERENCE_FILE)
    harm = load_harmonic(HARMONIC_FILE)

    all_diffs = []
    monthly = defaultdict(list)

    dates = sorted(set(ref.keys()) & set(harm.keys()))

    # ── Simple side-by-side per-day output ───────────────────────────────────
    with open('comparison_simple.txt', 'w') as f:
        for date in dates:
            f.write(f'{date}\n')
            harm_highs = [(t, h) for t, h, is_high, c in harm[date] if is_high]
            harm_lows  = [(t, h) for t, h, is_high, c in harm[date] if not is_high]
            ref_highs  = [(t, h) for t, h, is_high, c in ref[date]  if is_high]
            ref_lows   = [(t, h) for t, h, is_high, c in ref[date]  if not is_high]

            all_harm = sorted([(t, h, 'HT') for t,h in harm_highs] + [(t, h, 'LT') for t,h in harm_lows])
            all_ref  = sorted([(t, h, 'HT') for t,h in ref_highs]  + [(t, h, 'LT') for t,h in ref_lows])

            for (ht, hh, htype), (rt, rh, rtype) in zip(all_harm, all_ref):
                diff = round(time_diff_minutes(ht, rt))
                sign = f'+{diff}' if diff >= 0 else str(diff)
                f.write(f'  {htype}  maree.info: {fmt_time(rt)} {rh:.2f}m   harmonic: {fmt_time(ht)} {hh:.2f}m   diff: {sign} min\n')
            f.write('\n')

    print('Written to comparison_simple.txt')

    print(f'Comparing {len(dates)} days...\n')

    for date in dates:
        day_diffs = compare_day(harm[date], ref[date])
        all_diffs.extend(day_diffs)
        monthly[date.month].extend(day_diffs)

    # ── Overall stats ──────────────────────────────────────────────────────────
    def stats(values, label, unit):
        if not values:
            return
        mean = sum(values) / len(values)
        mx = max(values, key=abs)
        pos = sum(1 for v in values if v > 0)
        neg = sum(1 for v in values if v < 0)
        within1 = sum(1 for v in values if abs(v) <= 1) / len(values) * 100
        within2 = sum(1 for v in values if abs(v) <= 2) / len(values) * 100
        within5 = sum(1 for v in values if abs(v) <= 5) / len(values) * 100
        print(f'  {label}: mean={mean:+.2f}{unit}  max_err={mx:+.2f}{unit}  '
              f'bias={"+late" if mean>0 else "-early"}  '
              f'±1={within1:.0f}%  ±2={within2:.0f}%  ±5={within5:.0f}%')

    ht_time  = [d[1] for d in all_diffs if d[0] == 'HT']
    lt_time  = [d[1] for d in all_diffs if d[0] == 'LT']
    ht_height = [d[2] for d in all_diffs if d[0] == 'HT']
    lt_height = [d[2] for d in all_diffs if d[0] == 'LT']

    print('=' * 60)
    print('OVERALL SUMMARY (harmonic - reference)')
    print('=' * 60)
    print('Time errors (harmonic minus maree.info, + = late):')
    stats(ht_time, 'High tides', 'min')
    stats(lt_time, 'Low tides ', 'min')
    print('Height errors (harmonic minus maree.info, + = too high):')
    stats(ht_height, 'High tides', 'm')
    stats(lt_height, 'Low tides ', 'm')

    # ── Monthly breakdown ──────────────────────────────────────────────────────
    MONTHS = ['Jan','Feb','Mar','Apr','May','Jun',
              'Jul','Aug','Sep','Oct','Nov','Dec']
    print()
    print('MONTHLY TIME ERRORS (mean ± max, minutes):')
    print(f'  {"Month":<6}  {"HT mean":>8}  {"HT max":>8}  {"LT mean":>8}  {"LT max":>8}')
    for m in range(1, 13):
        diffs = monthly[m]
        if not diffs:
            continue
        ht = [d[1] for d in diffs if d[0] == 'HT']
        lt = [d[1] for d in diffs if d[0] == 'LT']
        ht_mean = sum(ht)/len(ht) if ht else 0
        lt_mean = sum(lt)/len(lt) if lt else 0
        ht_max  = max(ht, key=abs) if ht else 0
        lt_max  = max(lt, key=abs) if lt else 0
        print(f'  {MONTHS[m-1]:<6}  {ht_mean:>+8.1f}  {ht_max:>+8.1f}  {lt_mean:>+8.1f}  {lt_max:>+8.1f}')

    print()
    print('MONTHLY HEIGHT ERRORS (mean ± max, meters):')
    print(f'  {"Month":<6}  {"HT mean":>8}  {"HT max":>8}  {"LT mean":>8}  {"LT max":>8}')
    for m in range(1, 13):
        diffs = monthly[m]
        if not diffs:
            continue
        ht = [d[2] for d in diffs if d[0] == 'HT']
        lt = [d[2] for d in diffs if d[0] == 'LT']
        ht_mean = sum(ht)/len(ht) if ht else 0
        lt_mean = sum(lt)/len(lt) if lt else 0
        ht_max  = max(ht, key=abs) if ht else 0
        lt_max  = max(lt, key=abs) if lt else 0
        print(f'  {MONTHS[m-1]:<6}  {ht_mean:>+8.2f}  {ht_max:>+8.2f}  {lt_mean:>+8.2f}  {lt_max:>+8.2f}')

    # ── Per-day detail CSV ────────────────────────────────────────────────────
    detail_path = 'comparison_per_day.csv'
    with open(detail_path, 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['date',
                    'tide1_type','tide1_time_err_min','tide1_height_err_m',
                    'tide2_type','tide2_time_err_min','tide2_height_err_m',
                    'tide3_type','tide3_time_err_min','tide3_height_err_m',
                    'tide4_type','tide4_time_err_min','tide4_height_err_m',
                    'max_time_err_min','max_height_err_m'])
        for date in dates:
            day_diffs = compare_day(harm[date], ref[date])
            row = [str(date)]
            for d in day_diffs:
                row += [d[0], round(d[1], 1), round(d[2], 2)]
            # pad to 4 tides
            while len(row) < 1 + 4*3:
                row += ['', '', '']
            t_errs = [abs(d[1]) for d in day_diffs]
            h_errs = [abs(d[2]) for d in day_diffs]
            row += [round(max(t_errs), 1) if t_errs else '',
                    round(max(h_errs), 2) if h_errs else '']
            w.writerow(row)
    print(f'Per-day detail written to {detail_path}')

    # ── Worst 10 days ──────────────────────────────────────────────────────────
    day_max_err = {}
    for date in dates:
        day_diffs = compare_day(harm[date], ref[date])
        if day_diffs:
            day_max_err[date] = max(abs(d[1]) for d in day_diffs)

    worst = sorted(day_max_err, key=lambda d: -day_max_err[d])[:10]
    print()
    print('WORST 10 DAYS (by max time error):')
    print(f'  {"Date":<12}  {"MaxErr":>8}  {"Detail"}')
    for date in worst:
        day_diffs = compare_day(harm[date], ref[date])
        detail = '  '.join(f'{d[0]}:{d[1]:+.0f}m/{d[2]:+.2f}m' for d in day_diffs)
        print(f'  {str(date):<12}  {day_max_err[date]:>+8.1f}  {detail}')

    print()
    print('=' * 60)
    for t_tol, h_tol in [(2, 0.15), (5, 0.20), (10, 0.25)]:
        days_ok = sum(1 for d in dates if
                      all(abs(x[1]) <= t_tol and abs(x[2]) <= h_tol
                          for x in compare_day(harm[d], ref[d])))
        print(f'All tides within ±{t_tol}min AND ±{h_tol}m: '
              f'{days_ok}/{len(dates)} ({days_ok/len(dates)*100:.0f}%)')

    # Per-tide pass rate
    print()
    for t_tol in [2, 5, 10]:
        ht_ok = sum(1 for d in all_diffs if d[0]=='HT' and abs(d[1]) <= t_tol)
        lt_ok = sum(1 for d in all_diffs if d[0]=='LT' and abs(d[1]) <= t_tol)
        n_ht = sum(1 for d in all_diffs if d[0]=='HT')
        n_lt = sum(1 for d in all_diffs if d[0]=='LT')
        print(f'Individual tides within ±{t_tol}min:  '
              f'HT {ht_ok}/{n_ht} ({ht_ok/n_ht*100:.0f}%)  '
              f'LT {lt_ok}/{n_lt} ({lt_ok/n_lt*100:.0f}%)')


if __name__ == '__main__':
    main()
